FROM php:8.3-apache

RUN a2enmod rewrite

# Instala dependências do sistema e PHP
RUN apt-get update && \
    apt-get install -y \
    libzip-dev libxml2-dev zip unzip mariadb-client git \
    libfreetype6-dev libjpeg62-turbo-dev libpng-dev openssl \
    nodejs npm \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install pdo_mysql mysqli zip soap gd \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
ENV COMPOSER_ALLOW_SUPERUSER=1

# Configuração do Apache
# Copiar o arquivo vhost personalizado
COPY ./docker/vhost-hom.conf /etc/apache2/sites-available/gecon-nex-hom.conf

# Desabilitar o site padrão do Apache e habilitar o nosso
RUN a2dissite 000-default.conf && a2ensite gecon-nex-hom.conf

WORKDIR /var/www/html

# Copiar código
COPY . .

# Instalar dependências PHP
RUN composer install --no-dev --optimize-autoloader --no-interaction

# Build assets frontend
RUN npm ci && npm run build

# Permissões Laravel
RUN chown -R www-data:www-data storage bootstrap/cache && \
    chmod -R 775 storage bootstrap/cache

EXPOSE 80

CMD ["apache2-foreground"]
