version: '3'

services:
  app_hom:
    build:
      context: .
      dockerfile: Dockerfile-hom
    container_name: gecon-nex-hom
    ports:
      - "8081:80"
    volumes:
      - ./.env-hom:/var/www/html/.env
    environment:
      APP_ENV: hom
      APP_DEBUG: "true"
      APP_KEY: base64:d1ttqOkOWY7oou/sqptbl4+3/QdUL1bnOXjk8vBJlBk=
      DB_HOST: db_hom
      DB_DATABASE: gecon
      DB_USERNAME: root
      DB_PASSWORD: 123456
    depends_on:
      - db_hom

  db_hom:
    image: mysql:8.0
    container_name: mysql_gecon_hom
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: gecon
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - db_data_hom:/var/lib/mysql

volumes:
  db_data_hom:
