# Produção
<VirtualHost *:80>
    ServerName gecon-nex.com.br
    Redirect permanent / https://gecon-nex.com.br/
</VirtualHost>

<VirtualHost *:443>
    ServerName gecon-nex.com.br

    SSLEngine On
    SSLCertificateFile /etc/ssl/certs/fullchain.pem
    SSLCertificateKeyFile /etc/ssl/private/privkey.pem

    ProxyPreserveHost On
    ProxyPass / http://127.0.0.1:8000/
    ProxyPassReverse / http://127.0.0.1:8000/
</VirtualHost>

# Homologação
<VirtualHost *:80>
    ServerName teste.gecon-nex.com.br
    Redirect permanent / https://hom.gecon-nex.com.br/
</VirtualHost>

<VirtualHost *:443>
    ServerName teste.gecon-nex.com.br

    SSLEngine On
    SSLCertificateFile /etc/ssl/certs/fullchain-hom.pem
    SSLCertificateKeyFile /etc/ssl/private/privkey-hom.pem

    ProxyPreserveHost On
    ProxyPass / http://127.0.0.1:8081/
    ProxyPassReverse / http://127.0.0.1:8081/
</VirtualHost>
