# Produção
<VirtualHost *:80>
    ServerName gecon-nex.com.br
    Redirect permanent / https://gecon-nex.com.br/
</VirtualHost>

<VirtualHost *:443>
    ServerName gecon-nex.com.br

    SSLEngine on
    SSLCertificateFile /etc/apache2/ssl/apache.crt
    SSLCertificateKeyFile /etc/apache2/ssl/apache.key

    ProxyPreserveHost On
    ProxyPass / http://127.0.0.1:8000/
    ProxyPassReverse / http://127.0.0.1:8000/
</VirtualHost>

# Homologação
<VirtualHost *:80>
    ServerName teste.gecon-nex.com.br
    Redirect permanent / https://hom.gecon-nex.com.br/
</VirtualHost>

<VirtualHost *:443>
    ServerName teste.gecon-nex.com.br

    SSLEngine on
    SSLCertificateFile /etc/apache2/ssl/apache.crt
    SSLCertificateKeyFile /etc/apache2/ssl/apache.key


    ProxyPreserveHost On
    ProxyPass / http://127.0.0.1:8081/
    ProxyPassReverse / http://127.0.0.1:8081/
</VirtualHost>
